from __future__ import annotations

import argparse
from datetime import UTC, datetime
import random
import shutil
import sys
import time
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "src"))

from rag_vs_pag.jsonio import write_json
from rag_vs_pag.text import normalize_space, redact_pii, strip_request_boilerplate
from scripts.corpus_build.extract_gold_labels import extract_exemptions
from scripts.corpus_build.muckrock_client import MuckRockClient, PublicMuckRockClient


def absolute_url(slug: str) -> str:
    return f"https://www.muckrock.com/foi/{slug}/" if slug else ""


def unique_exemptions(exemptions: list[str]) -> list[str]:
    distinct: list[str] = []
    for exemption in exemptions:
        if exemption not in distinct:
            distinct.append(exemption)
    return distinct


def substantive(text: str) -> str:
    text = text.replace("**THIS EMAIL BOX IS NOT MONITORED, PLEASE DO NOT REPLY TO THIS EMAIL.**", " ")
    return normalize_space(text)


APPENDIX_MARKERS = (
    "EXPLANATION OF EXEMPTIONS",
    "SUBSECTIONS OF TITLE 5, UNITED STATES CODE, SECTION 552",
    "FBI FOIPA Addendum",
    "Privacy Act Exemptions",
    "FOIA Exemptions",
)

DENIAL_CUES = (
    "withheld",
    "withhold",
    "denied",
    "exempt",
    "pursuant to exemption",
    "neither confirm nor deny",
    "could reasonably be expected",
    "redacted",
)


class Scraper:
    def __init__(self, sleep: float, authenticated: bool) -> None:
        self.client = MuckRockClient.from_env() if authenticated else PublicMuckRockClient()
        self.sleep = sleep
        self.calls = 0
        self.agencies: dict[int, dict] = {}
        self.files: dict[int, dict] = {}

    def get(self, path: str, params: dict | None = None) -> dict:
        payload = self.client.get(path, params)
        self.calls += 1
        if self.sleep:
            time.sleep(self.sleep)
        return payload

    def agency(self, agency_id: int) -> dict:
        if agency_id not in self.agencies:
            self.agencies[agency_id] = self.get(f"agencies/{agency_id}/")
        return self.agencies[agency_id]

    def file(self, file_id: int) -> dict:
        if file_id not in self.files:
            self.files[file_id] = self.get(f"files/{file_id}/")
        return self.files[file_id]

    def download_file(self, url: str) -> bytes:
        data = self.client.download(url)
        if self.sleep:
            time.sleep(self.sleep)
        return data

    def communications(self, foia_id: int) -> list[dict]:
        rows: list[dict] = []
        page = 1
        while True:
            payload = self.get(
                "communications/",
                {
                    "foia": foia_id,
                    "autogenerated": "false",
                    "page_size": 100,
                    "page": page,
                },
            )
            rows.extend(payload.get("results", []))
            if not payload.get("next"):
                return rows
            page += 1


def safe_file_name(file_id: int, url: str) -> str:
    suffix = Path(url.split("?", 1)[0]).suffix.lower()
    if suffix not in {".pdf", ".txt"}:
        suffix = ".bin"
    return f"{file_id}{suffix}"


def truncate_appendix(text: str) -> str:
    cut = len(text)
    for marker in APPENDIX_MARKERS:
        idx = text.find(marker)
        if idx != -1:
            cut = min(cut, idx)
    return text[:cut]


def has_denial_cue(text: str) -> bool:
    lower = text.lower()
    return any(cue in lower for cue in DENIAL_CUES)


def pdf_to_text(path: Path) -> str:
    if not shutil.which("pdftotext"):
        raise RuntimeError("pdftotext is required for --include-files")
    completed = subprocess.run(
        ["pdftotext", str(path), "-"],
        text=True,
        capture_output=True,
        check=False,
    )
    if completed.returncode != 0:
        return ""
    return completed.stdout


def file_text(scraper: Scraper, file_id: int, cache_dir: Path, max_pages: int) -> tuple[str, dict | None]:
    metadata = scraper.file(file_id)
    pages = metadata.get("pages")
    if isinstance(pages, int) and pages > max_pages:
        return "", metadata
    url = metadata.get("ffile") or ""
    if not url:
        return "", metadata
    cache_dir.mkdir(parents=True, exist_ok=True)
    target = cache_dir / safe_file_name(file_id, url)
    if not target.exists():
        target.write_bytes(scraper.download_file(url))
    if target.suffix.lower() == ".pdf":
        text = pdf_to_text(target)
    else:
        text = target.read_text(encoding="utf-8", errors="replace")
    return substantive(truncate_appendix(text)), metadata


def response_candidates_with_sources(
    scraper: Scraper,
    response_candidates: list[dict],
    include_files: bool,
    file_cache: Path,
    max_files_per_request: int,
    max_file_pages: int,
) -> list[dict]:
    candidates: list[dict] = []
    for comm in reversed(response_candidates):
        text = substantive(comm.get("communication") or "")
        candidates.append(
            {
                "source": "communication_text",
                "communication": comm,
                "text": text,
                "file_metadata": None,
            }
        )
        if not include_files:
            continue
        for file_id in (comm.get("files") or [])[:max_files_per_request]:
            try:
                text, metadata = file_text(scraper, int(file_id), file_cache, max_file_pages)
            except Exception:
                continue
            if text:
                candidates.append(
                    {
                        "source": "file_pdf_text",
                        "communication": comm,
                        "text": text,
                        "file_metadata": metadata,
                    }
                )
    return candidates


def record_from_request(
    scraper: Scraper,
    item: dict,
    retrieved_at: str,
    redact: bool,
    include_files: bool,
    file_cache: Path,
    max_files_per_request: int,
    max_file_pages: int,
) -> tuple[dict | None, str]:
    if item.get("embargo_status") != "public":
        return None, "not_public"

    comms = scraper.communications(int(item["id"]))
    request_candidates = [
        comm for comm in comms if not comm.get("response") and not comm.get("autogenerated")
    ]
    response_candidates = [
        comm for comm in comms if comm.get("response") and not comm.get("autogenerated")
    ]
    if not response_candidates:
        return None, "no_response_comm"

    request_text_raw = ""
    if request_candidates:
        request_candidates.sort(key=lambda row: row.get("datetime") or "")
        request_text_raw = request_candidates[0].get("communication") or ""
    request_text = strip_request_boilerplate(request_text_raw or item.get("requested_docs") or "")
    if len(request_text) < 200:
        return None, "short_request_text"

    response_candidates.sort(key=lambda row: row.get("datetime") or "")
    cited_response = None
    cited_exemptions: list[str] = []
    cited_source = ""
    cited_file_metadata = None
    for candidate in response_candidates_with_sources(
        scraper,
        response_candidates,
        include_files,
        file_cache,
        max_files_per_request,
        max_file_pages,
    ):
        response_text = candidate["text"]
        exemptions = unique_exemptions(extract_exemptions(response_text))
        if len(response_text) >= 300 and exemptions and has_denial_cue(response_text) and len(exemptions) <= 4:
            cited_response = candidate["communication"]
            cited_exemptions = exemptions
            cited_source = candidate["source"]
            cited_file_metadata = candidate["file_metadata"]
            break
    if not cited_response:
        return None, "no_substantive_exemption_response"

    agency_id = int(item.get("agency") or 0)
    agency = scraper.agency(agency_id) if agency_id else {}
    if cited_source == "file_pdf_text" and cited_file_metadata:
        response_text, _ = file_text(scraper, int(cited_file_metadata["id"]), file_cache, max_file_pages)
    else:
        response_text = substantive(cited_response.get("communication") or "")
    if redact:
        request_text = redact_pii(request_text)
        response_text = redact_pii(response_text)

    return (
        {
            "id": int(item["id"]),
            "muckrock_url": absolute_url(item.get("slug", "")),
            "agency_name": agency.get("name") or f"agency:{agency_id}",
            "agency_id": agency_id,
            "filed_date": str(item.get("datetime_submitted") or "")[:10],
            "status": item.get("status") or "",
            "request_text": request_text,
            "response_text": response_text,
            "primary_exemption": cited_exemptions[0],
            "all_cited_exemptions": cited_exemptions,
            "extraction_confidence": "regex",
            "response_source": cited_source,
            "response_comm_id": cited_response.get("id"),
            "response_file_id": cited_file_metadata.get("id") if cited_file_metadata else None,
            "response_file_url": cited_file_metadata.get("ffile") if cited_file_metadata else None,
            "retrieved_at": retrieved_at,
        },
        "kept",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="scenarios/muckrock_snapshot.live.json")
    parser.add_argument("--report", default="scenarios/muckrock_selection_report.live.json")
    parser.add_argument("--limit", type=int, default=100)
    parser.add_argument("--max-requests", type=int, default=750)
    parser.add_argument("--sleep", type=float, default=1.0)
    parser.add_argument("--page-size", type=int, default=50)
    parser.add_argument("--start-page", type=int, default=1)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--status", action="append", choices=["partial", "rejected"])
    parser.add_argument("--authenticated", action="store_true")
    parser.add_argument("--no-redact", action="store_true")
    parser.add_argument("--include-files", action="store_true")
    parser.add_argument("--file-cache", default="scenarios/archive/muckrock_file_cache")
    parser.add_argument("--max-files-per-request", type=int, default=3)
    parser.add_argument("--max-file-pages", type=int, default=8)
    args = parser.parse_args()

    statuses = args.status or ["partial", "rejected"]
    scraper = Scraper(sleep=args.sleep, authenticated=args.authenticated)
    retrieved_at = datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    rows = []
    seen_prefixes: set[str] = set()
    counts: dict[str, int] = {"seen": 0, "kept": 0}
    rng = random.Random(args.seed)

    for status in statuses:
        page = args.start_page
        while counts["seen"] < args.max_requests and len(rows) < args.limit:
            payload = scraper.get(
                "requests/",
                {
                    "jurisdiction": 10,
                    "status": status,
                    "page_size": args.page_size,
                    "page": page,
                },
            )
            results = payload.get("results", [])
            if not results:
                break
            rng.shuffle(results)
            for item in results:
                if counts["seen"] >= args.max_requests or len(rows) >= args.limit:
                    break
                counts["seen"] += 1
                record, reason = record_from_request(
                    scraper,
                    item,
                    retrieved_at,
                    redact=not args.no_redact,
                    include_files=args.include_files,
                    file_cache=Path(args.file_cache),
                    max_files_per_request=args.max_files_per_request,
                    max_file_pages=args.max_file_pages,
                )
                counts[reason] = counts.get(reason, 0) + 1
                if not record:
                    continue
                prefix = normalize_space(record["request_text"].lower())[:200]
                if prefix in seen_prefixes:
                    counts["duplicate_prefix"] = counts.get("duplicate_prefix", 0) + 1
                    continue
                seen_prefixes.add(prefix)
                rows.append(record)
                counts["kept"] = len(rows)
                print(
                    f"kept {len(rows)}/{args.limit}: {record['id']} "
                    f"{record['primary_exemption']} {record['agency_name']}",
                    flush=True,
                )
            if not payload.get("next"):
                break
            page += 1

    write_json(args.output, rows)
    write_json(
        args.report,
        {
            "retrieved_at": retrieved_at,
            "api": "https://www.muckrock.com/api_v2/",
            "statuses": statuses,
            "limit": args.limit,
            "max_requests": args.max_requests,
            "sleep": args.sleep,
            "page_size": args.page_size,
            "start_page": args.start_page,
            "include_files": args.include_files,
            "file_cache": args.file_cache if args.include_files else None,
            "max_files_per_request": args.max_files_per_request,
            "max_file_pages": args.max_file_pages,
            "counts": counts,
            "api_calls": scraper.calls,
        },
    )
    print(f"wrote {len(rows)} rows to {args.output}")
    print(f"wrote report to {args.report}")


if __name__ == "__main__":
    main()
