"""Regenerate pearl/traces_review.md alongside the generated traces.csv.

For every row, render:
  - the label
  - the source cite (points into the statute or DOJ Guide)
  - the VERBATIM STATUTE PARAGRAPH for that exemption (when applicable)
  - the feature expansion with each TRUE feature's full statute-anchored label

This is the human audit surface. Any claim the pearl makes at runtime
must be traceable through this document back to the quoted statute.
"""
from __future__ import annotations

import csv
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent
PROJECT = ROOT.parent
FD_PATH = ROOT / "feature_dictionary.json"
TRACES = ROOT / "traces.csv"
REVIEW = ROOT / "traces_review.md"

META_COLS = {"exemption", "source", "note"}


def _load_statute_paragraphs() -> dict[int, str]:
    from pearl.generate_traces import _load_statute_text, extract_exemption_paragraphs

    return extract_exemption_paragraphs(_load_statute_text())


def main() -> int:
    fd = json.loads(FD_PATH.read_text())
    rows = list(csv.DictReader(TRACES.open()))
    paragraphs = _load_statute_paragraphs()

    # Validate column set.
    if rows:
        cols = set(rows[0].keys())
        unknown = cols - META_COLS - set(fd)
        if unknown:
            print(f"unknown columns in traces.csv: {sorted(unknown)}", file=sys.stderr)
            return 1

    lines = [
        "# Traces Review",
        "",
        f"Source: `pearl/traces.csv` ({len(rows)} rows), generated by",
        "`pearl/generate_traces.py` from the fetched statute corpus and the",
        "feature dictionary. No row was hand-typed.",
        "",
        "The trust boundary of the pearl is the feature dictionary — the",
        "mapping from human-readable feature names to their cited clauses of",
        "5 U.S.C. § 552(b). Every exemplar below is accompanied by the",
        "verbatim statute paragraph it is derived from. Read each quote and",
        "confirm the TRUE features fairly summarize its named elements.",
        "",
        "## Exemplars",
        "",
    ]

    counts: dict[str, int] = {}
    for i, r in enumerate(rows, start=1):
        label = r["exemption"]
        counts[label] = counts.get(label, 0) + 1
        lines.append(f"### Row {i} — `{label}`")
        lines.append("")
        lines.append(f"- **Source:** {r['source']}")
        lines.append(f"- **Note:** {r['note']}")

        # If this row maps to a (b)(N), quote the verbatim statute paragraph.
        m = re.match(r"b(\d)", label)
        if m and int(m.group(1)) in paragraphs:
            n = int(m.group(1))
            para = re.sub(r"\s+", " ", paragraphs[n]).strip()
            lines.append("- **Verbatim statute text:**")
            lines.append("  ")
            lines.append(f"  > {para}")
        lines.append("")

        true_keys = [k for k in fd if r.get(k, "").strip().lower() == "true"]
        if true_keys:
            lines.append("- **Features TRUE:**")
            for k in true_keys:
                lines.append(f"  - `{k}` — {fd[k]['label']} ({fd[k]['cite']})")
        else:
            lines.append("- **Features TRUE:** _(none — all false)_")
        lines.append("")

    lines.append("## Label distribution")
    lines.append("")
    for label, n in sorted(counts.items()):
        lines.append(f"- `{label}`: {n}")
    lines.append("")
    lines.append("## Feature dictionary (the trust boundary)")
    lines.append("")
    lines.append("Each feature below is derived from a specific clause of")
    lines.append("§ 552(b). The `cite` column is the pinpoint cite; the `label`")
    lines.append("is the human-readable name used in runtime explanations and in")
    lines.append("the `--explain` output of `logicpearl run`.")
    lines.append("")
    lines.append("| feature | label | cite |")
    lines.append("|---|---|---|")
    for k, meta in fd.items():
        lines.append(f"| `{k}` | {meta['label']} | {meta['cite']} |")
    lines.append("")

    REVIEW.write_text("\n".join(lines))
    print(f"wrote {REVIEW}  ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
